VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "classFeatureLoad"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Temporary feature load class. '

Option Explicit

Public Used As Boolean

Public World As String
Public Category As String
Public Feature As String
Public Filename As String
Public Seqname As String
Public FootprintX As Long
Public FootprintY As Long
Public Objectname As String

